### ISSUE TITLE
lpf-flash-plugin fails--maybe can't download source

### ISSUE THREAD

**Issue by KenJackson** [leamas/lpf#33]
I have these installed in Fedora 26:
    lpf-0.2-4.f1f5dd9.fc26.noarch
    lpf-flash-plugin-27.0.0.183-1.fc26.x86_64
The "id" command shows that my user is in the "pkg-build" group.

I ran the command "lpf update".  A popup offered to update flash-plugin.  I clicked for it to proceed. Another popup, labeled "lpf: flash-plugin", has a green circle in front of "Install build dependencies" and a circling twirly in front of "Download sources".  It never completes.  I eventually clicked "Cancel".

As an aside, lots of Gtk-Message warnings spill into my terminal:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/usr/share/lpf/scripts/update.py:10: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/usr/share/lpf/scripts/build_error.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk        # pylint:disable=no-name-in-module
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Amidst all the Gtk warnings are these:
flash-plugin: downloading sources
flash-plugin: build failed
flash-plugin: build errors
flash-plugin: exiting

I don't think it successfully downloaded anything.  This directory is empty:
/usr/share/lpf/packages/flash-plugin/SOURCES
I clicked to view the log, but it didn't show anything and I can't find a log anywhere.

**Comment by sergiomb2** [comment]
Hi, 
Thanks for the feedback, please attach /var/lib/lpf/log/flash-plugin.log in this file is the answer  .

Thanks

**Comment by KenJackson** [comment]
[flash-plugin.log](https://github.com/leamas/lpf/files/1471968/flash-plugin.log)
OK.  So that's where the log is.  Attached.
Ah!  The log says "curl: (22) The requested URL returned error: 404 Not Found".
The URL is:
http://fpdownload.macromedia.com/get/flashplayer/pdc/27.0.0.183/flash_player_npapi_linux.i386.tar.gz

**Comment by KenJackson** [comment]
Both of these links are good:
https://fpdownload.macromedia.com/pub/labs/flashruntimes/flashplayer/linux64/flash_player_npapi_linux.x86_64.tar.gz
https://fpdownload.macromedia.com/pub/labs/flashruntimes/flashplayer/linux32/flash_player_npapi_linux.i386.tar.gz

I got these links from this page:  http://labs.adobe.com/downloads/flashplayer.html

Also, I don't understand why lpf was trying to download the i386 source when my system is x86_64 and the correct source is available.

**Comment by sergiomb2** [comment]
yes , mystery solved  the flash version now is 27.0.0.187 , I going update flash-plugin 
the correct link now is 
http://fpdownload.macromedia.com/get/flashplayer/pdc/27.0.0.187/flash_player_npapi_linux.i386.tar.gz

**Comment by sergiomb2** [comment]
this one [1] version is 28.0.0.105 ! 

[1]
https://fpdownload.macromedia.com/pub/labs/flashruntimes/flashplayer/linux32/flash_player_npapi_linux.i386.tar.gz

**Comment by sergiomb2** [comment]
anyway both versions doesn't work on Firefox 57 quantum

**Comment by sergiomb2** [comment]
Hi , I hadn't luck I had checked flash plugin in one site that have all videos broken , with other site it works , I'm updating  lpf-flash-plugin-27.0.0.187 now [1] 
 [1] 
http://koji.rpmfusion.org/koji/packageinfo?packageID=342

**Comment by sergiomb2** [comment]
Is working now , after fixed some bug in spec (some tie ago) 
ths ticket can be closed

**Comment by sergiomb2** [comment]
lpf-flash-plugin (or other lpf packge) fails to download source, please report on rpmfusion.org [1]  (bugzilla or mailing list etc) 

[1] 
https://bugzilla.rpmfusion.org/enter_bug.cgi?product=Fedora&component=lpf-flash-plugin

**Comment by sergiomb2** [comment]
and you may close this issue as fixed (I don't have permissions to do that) Thanks
